# Generated by Django 4.2.4 on 2023-08-08 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SiteScraper", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="link", old_name="addres", new_name="address",
        ),
    ]
